//CHARACTERS 
export const CHARACTER_GET_SUCCESS = 'CHARACTER_GET_SUCCESS'
export const CHARACTER_FAIL = 'CHARACTER_FAIL' 

//EPISODES
export const EPISODES_GET_SUCCESS = 'EPISODES_GET_SUCCESS'
export const EPISODES_FAIL = 'EPISODES_FAIL' 